### ISSUE TITLE
"Copy as" colors

### ISSUE THREAD

**Issue by kerim** [santiyounger/Cobra#1]
This theme has done pretty well even as Logseq continues to change, but one area where it falls short is the "copy as" window. It outputs yellow text on a white background which makes it hard to see what is in the dialog box. If you get a chance to upgrade this it would be much appreciated. I love this theme!

**Comment by santiyounger** [comment]
hey thanks, happy to know you like it! would you might sharing some screenshots to make sure I know what you mean. Thanks a lot!

**Comment by kerim** [comment]
Actually, this was fixed in a recent Logseq update - they even listed it as a fix... something like "black screen for copy as in dark mode" (I don't remember exactly which version or the precise wording). Marking this as closed.

**Comment by santiyounger** [comment]
awesome thanks for letting me know @kerim happy to know things are working!!
