### ISSUE TITLE
stopped working since at least 0.6.6

### ISSUE THREAD

**Issue by lef-est** [santiyounger/Cobra#5]
I tried to toggle `t t` several times but it still looks similar to the default theme.

**Comment by santiyounger** [comment]
thanks for letting me know, I just upgraded Logseq and you are right, there is some strange conflict with my theme's dark mode.

I'll keep you updated here once I can find a solution

**Comment by mvidallopez** [comment]
> thanks for letting me know, I just upgraded Logseq and you are right, there is some strange conflict with my theme's dark mode.
> 
> I'll keep you updated here once I can find a solution

FYI it works again with v0.6,7. I thank you for your great theme, Santi!

**Comment by lef-est** [comment]
Yes now it works! Yay!

**Comment by santiyounger** [comment]
This is hilarious, seems like my manual fixes actually broke the theme again. I'll re-fix it (supposably by undoing what I changed) I'll keep you updated here

**Comment by santiyounger** [comment]
okay it should be fixed now again, do let me know if anyone experiences any issues with Logseq 0.6.7 (latest version atm)

Thanks guys!
